#!/bin/sh

uci -q batch <<-EOF >/dev/null
# /etc/config/system
    set system.@system[0].timezone='CST-8'
    set system.@system[0].zonename='Asia/Shanghai'
    commit system

# /etc/config/network
    set network.lan.ipaddr='192.168.5.1'
    commit network

# /etc/config/wireless
    set wireless.@wifi-iface[0].disabled="0"

    commit wireless

# /etc/config/smartdns
    #set smartdns.@smartdns[0].enabled='1'
    # for openwrt-22.03
    set smartdns.@smartdns[0].port='6053'
    # for openwrt-22.03
    
# /etc/config/dhcp
    #add_list dhcp.@dnsmasq[0].server='127.0.0.1#6053'
    #set dhcp.@dnsmasq[0].noresolv='1'

    #set dhcp.lan.ra='relay'
    #set dhcp.lan.dhcpv6='relay'
    #set dhcp.lan.ndp='relay'

    #set dhcp.wan6=dhcp
    #set dhcp.wan6.interface='wan6'
    #set dhcp.wan6.ignore='1'
    #set dhcp.wan6.master='1'
    #set dhcp.wan6.ra='relay'
    #set dhcp.wan6.dhcpv6='relay'
    #set dhcp.wan6.ndp='relay'

    #commit dhcp

# /etc/config/AdGuardHome
    #set AdGuardHome.AdGuardHome.enabled='1'
    #set AdGuardHome.AdGuardHome.redirect='redirect'
    #commit AdGuardHome

# /etc/config/adblock
    set adblock.global.adb_triggerdelay='120'
    commit adblock


# /etc/config/sqm
    #set sqm.eth1.enabled='1'
    #set sqm.eth1.interface='wan'
    #set sqm.eth1.download='300000'
    #set sqm.eth1.upload='30000'
    #commit sqm
EOF

cat >> /etc/smartdns/custom.conf <<-EOF

# dns cache size
#cache-size 12288

# enable persist cache when restart
cache-persist yes

# cache persist file
cache-file /var/etc/smartdns/smartdns.cache

# prefetch domain
#prefetch-domain yes
serve-expired-prefetch-time 43200

# cache serve expired
#serve-expired yes

# cache serve expired TTL
serve-expired-ttl 345600

# force specific qtype return soa
#force-qtype-SOA 65

# ttl for all resource record
# rr-ttl-min: minimum ttl for resource record
#rr-ttl-min 600

# Support reading dnsmasq dhcp file to resolve local hostname
#dnsmasq-lease-file /tmp/dhcp.leases

EOF

#passwd root <<EOF
#password
#password
#EOF

sed -i '/^cn$/d' /usr/share/passwall/rules/direct_host
sed -i 's/geosite:cn/geosite:geolocation-cn/g' /usr/share/passwall/0_default_config

sed -i '/passwall/d ; /helloworld/d ; /openclash/d' /etc/opkg/distfeeds.conf

exit 0
